name: Deploy via SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Add version Tag
        run: echo "v12.19.$(date+'%Y%m%d').$(date+'%H%M')" > ./src/version.txt

      - name: Deploy files
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASSWORD }}
          server: ${{ secrets.SFTP_HOST }}
          # ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: './src/*'  # Specify the path to your files
          remote_path: '/customers/c/3/d/rockrullarna.se/httpd.www/' # Specify the remote path (wwwroot)
          sftp_only: true # Optional: If true, only SFTP will be used. If false, SCP will be used. Default is false (denna krävs som true för att fungera med one.com)
          sftpArgs: '-o ConnectTimeout=15'
